### ISSUE TITLE
[T03] Client connects to server

### ISSUE THREAD

**Issue by Debskij** [krzysztofzajaczkowski/HammerJack#3]
Client connects to server, send and receive keep-alive pings, if server dies client rise exception

**Comment by krzysztofzajaczkowski** [comment]
Client sends JOIN_QUEUE message to server, and expects one of these two responses:

- JOINED_QUEUE

- REJECTED_QUEUE

If succeed, client starts waiting for information about other players he should connect to, with option to leave queue early with message "LEAVE_QUEUE". Otherwise, if server's respond is REJECTED_QUEUE, client shuts down.

**Comment by krzysztofzajaczkowski** [comment]
Change of plans, got to adjust to server. Sending GAME_STATE as message to join queue and as keep alive. If server responds with interger - it's place in queue. If response is a list - then it's a list of players in create game.
